---
name: Template-Plugin-Text-Widont
version: 0.01
author:
  - 'Dave Cardwell <dcardwell@cpan.org>'
abstract: A Template Toolkit filter for removing typographic widows
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Template::Plugin::Filter: 0
  Text::Widont: 0
build_requires:
  Template: 2.07
  Test::More: 0
provides:
  Template::Plugin::Text::Widont:
    file: lib/Template/Plugin/Text/Widont.pm
    version: 0.01
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
